- name: Setting up variables
  hosts: all 
  gather_facts: False
  connection: local
  run_once: True
  become: no
  vars:
    production_list: "[ 'prod', 'prod1', 'prod1-canary', 'prod2', 'prod2-canary', 'phx', 'phx1', 'phx2' ]"
  vars_files:
    - ../../group_vars/argo_env.yml
 
  tasks:    
    - block:
      - name: Setting up closure date (in GMT)
        shell: "date --iso-8601='seconds' -d '+5 hour +2 second' | cut -c1-19"
        register: closure_date
      - debug: msg={{ closure_date.stdout }}

      - pause:
          prompt: "Can CRQ {{ result.json.response.change_number }} be closed? Please answer ('Yes' or 'No')"
        register: answer
     
      - name: close CRQ
        ignore_errors: yes
        register: closure_result
        uri:
          url: "https://release.company/api/v4/crq/{{ result.json.response.change_number }}/close"
          validate_certs: False
          method: POST
          user: "{{ sea_user.user_input }}"
          password: "{{ sea_password.user_input }}"
          force_basic_auth: yes
          body_format: json
          body: '{"start_date": "{{ start_date.stdout }}","end_date": "{{ closure_date.stdout }}", "deployments": [{"datacenter": "Chandler","environment": "Prod","status": "Successful"}],"closure_notes": "Done"}'
        delegate_to: labshop.company
        when: answer.user_input == "Yes" 

      - name: if CRQ hasn't been closed
        debug:
          msg: "CRQ cannot be closed for {{ instance_component }}"
        failed_when: closure_result.json.status_code != 200

      - name: if CRQ has been closed with status SUCCESS!
        debug:
          msg: "CRQ {{ result.json.response.change_number }} closed"
        when: closure_result.json.status_code == 200
      when: instance_stack in production_list
